### ISSUE TITLE
${input.name} instead of ${on_string}

### ISSUE THREAD

**Issue by lecorguille** [fls-bioinformatics-core/galaxy-tools#1]
Hi,
You do a great job. I was to lazy to wrap Trimmomatic although my colleagues regulary heat me :)

I'm running a RNASeq project on Galaxy to try Galaxy. I manage two instances since 3 years but I did'nt really use it. cli is so cool :)

So, I have just a suggestion on your wrapper to ease reading of ouputs:
<data format="fastqsanger" name="fastq_out_r1_paired" label="${input.name} ${tool.name} (R1 paired)">
Like that you keep a link with the input and use don't need to rename its dataset.

It's just a suggestion :)

Cheers

Gildas

**Comment by lecorguille** [comment]
So:
Origin
label="${tool.name} on ${on_string} (R1 paired)"
-> Trimmomatic on data 1 and data 2 (R1 paired)

Proposal
label="${paired_end.fastq_r1_in.name} ${tool.name} (R1 paired)"
-> PgC-5_S3_L001_R1_001.fastq Trimmomatic (R1 paired)

**Comment by pjbriggs** [comment]
@lecorguille thanks for this suggestion & apologies for not implementing it sooner - it has been added along with a set of other major changes to the `trimmomatic` tool, and also uploaded to the Galaxy toolshed:

https://toolshed.g2.bx.psu.edu/view/pjbriggs/trimmomatic/f8a9a5eaca8a
