### ISSUE TITLE
macs21 missing paired-end support

### ISSUE THREAD

**Issue by mictadlo** [fls-bioinformatics-core/galaxy-tools#10]
Hi @pjbriggs,
Could you please add to your `macs21` wrapper paired-end support?

Thank you in advance.

Mic

**Comment by pjbriggs** [comment]
@mictadlo I've made changes in pull request #11 to address this. I'll let you know when the updated version is available in the tool shed.

**Comment by pjbriggs** [comment]
@mictadlo the tool has been updated and the latest version has been pushed to the main and test toolsheds.

The update adds a new option for the user to explicitly select the type of input (e.g. single-ended BED, paired-end BAM etc) which is then passed to `macs` at run time.
