### ISSUE TITLE
Macs21 enable bdgdiff

### ISSUE THREAD

**Issue by mictadlo** [fls-bioinformatics-core/galaxy-tools#15]
Hi @pjbriggs,
Could you please enable in your MACS21 wrapper bdgdiff?

Best wishes,

Mic

**Comment by pjbriggs** [comment]
Hello @mictadlo 

Thanks for your request, unfortunately I'm not sure that this will be a very high priority for us at the moment so I can't promise anything soon.

However in the meantime it may be worth looking at the IUC `macs2` wrappers:

https://toolshed.g2.bx.psu.edu/view/iuc/macs2/6d4babad010f

which appears to include a `bdgdiff` wrapper along with many other MACS2 functions. So perhaps this would suit your requirements for now.

Best wishes

Peter
