### ISSUE TITLE
Unable to access jarfile /trimmomatic-0.32.jar

### ISSUE THREAD

**Issue by afgane** [fls-bioinformatics-core/galaxy-tools#21]
Hi, 
We just installed the latest revision of the Trimmomatic tool available in the Tool Shed (revision [4:14d05f2d511d](https://toolshed.g2.bx.psu.edu/repository?repository_id=ef9e620e9ac844b3)) and are getting the following error when trying to run the tool:

```
discarding /opt/galaxy/tool_dependencies/_conda/bin from PATH
prepending /opt/galaxy/galaxy-app/database/jobs/000/32/conda-env/bin to PATH
Arguments:
* -mx8G
* -jar
* /trimmomatic-0.32.jar
* PE
* -threads
* 24
* -phred33
* /opt/galaxy/galaxy-app/database/datasets/000/dataset_1.dat
* /opt/galaxy/galaxy-app/database/datasets/000/dataset_2.dat
* /opt/galaxy/galaxy-app/database/datasets/000/dataset_36.dat
* /opt/galaxy/galaxy-app/database/datasets/000/dataset_38.dat
* /opt/galaxy/galaxy-app/database/datasets/000/dataset_37.dat
* /opt/galaxy/galaxy-app/database/datasets/000/dataset_39.dat
* SLIDINGWINDOW:4:20
Error: Unable to access jarfile /trimmomatic-0.32.jar
Exit status: 0
```

Any suggestions on how to resolve this?

**Comment by pjbriggs** [comment]
Hello @afgane 

The tool command uses an environment variable `TRIMMOMATIC_DIR` to locate the Trimmomatic jar file, in the `<command>` section of `trimmomatic.xml`:

      trimmomatic.sh
     -mx8G
     -jar \$TRIMMOMATIC_DIR/trimmomatic-0.36.jar
     ...

When the tool is installed from the tool shed this should be defined in the generated `env.sh` file, but it's looks like it's missing from the context being used in your failing example above.

There is also a second variable `TRIMMOMATIC_ADAPTERS` which is used to locate the adapter files distributed with Trimmomatic.

Does this help? I don't have any experience with the conda resolvers that it appears you're using, so I'm not sure what to suggest as a fix.

**Comment by afgane** [comment]
This may be caused by the way Conda vs. non-Conda tool execution works.

To start, everything looks fine from what you described:
```
$ cat env.sh
TRIMMOMATIC_DIR=/opt/galaxy/tool_dependencies/trimmomatic/0.36/pjbriggs/trimmomatic/14d05f2d511d; export TRIMMOMATIC_DIR
TRIMMOMATIC_ROOT_DIR=/opt/galaxy/tool_dependencies/trimmomatic/0.36/pjbriggs/trimmomatic/14d05f2d511d; export TRIMMOMATIC_ROOT_DIR
TRIMMOMATIC_ADAPTERS_DIR=/opt/galaxy/tool_dependencies/trimmomatic/0.36/pjbriggs/trimmomatic/14d05f2d511d/adapters; export TRIMMOMATIC_ADAPTERS_DIR

$ ll /opt/galaxy/tool_dependencies/trimmomatic/0.36/pjbriggs/trimmomatic/14d05f2d511d/
total 132
drwxr-xr-x 2 galaxy users   4096 Sep 14 05:20 adapters
-rwxr-xr-x 1 galaxy users    399 Sep 14 05:20 env.sh
-rw-r--r-- 1 galaxy users 126230 Sep 14 05:20 trimmomatic-0.36.jar
```

When Galaxy executes the tool, the invocation command looks like this 
```
. /opt/galaxy/tool_dependencies/_conda/bin/activate '/opt/galaxy/galaxy-app/database/jobs/000/3/conda-env' 2>&1 ; bash /opt/galaxy/shed_tools/toolshed.g2.bx.psu.edu/repos/pjbriggs/trimmomatic/14d05f2d511d/trimmomatic/trimmomatic.sh -mx8G -jar $TRIMMOMATIC_DIR/trimmomatic-0.36.jar ...
```

So it seems it's activating the Conda env vs. sourcing the tool's `env.sh`. If I follow the same example and activate the Conda env manually, `trimmomatic` command becomes available on the shell directly, without needing to use a wrapper and supply a path to the jar file:
```
$ . bin/activate /opt/galaxy/galaxy-app/database/jobs/000/3/conda-env
discarding /opt/galaxy/tool_dependencies/_conda/bin from PATH
prepending /opt/galaxy/galaxy-app/database/jobs/000/3/conda-env/bin to PATH
$ trimmomatic -version
0.36
```

Would this mean the tool, as written now, is not be usable with Conda as the dependency resolver? If so, I wonder how should tools be written so they can be interchangeably used with different Galaxy setups...

(re. versions, two latest revisions are installed and they both experience the same behavior I just copied the error from rev 3)

**Comment by pjbriggs** [comment]
Thanks for the additional information (and clarification re the versions).

I'm not very familiar with conda, however: it appears that (bio?)conda, provides a `trimmomatic` command which is a wrapper script that handles the invocation of the jar file (which seems to be under `...share/trimmomatic/` in the conda environment - btw it looks like the `adapters` dir is also installed under that directory).

This script looks to be unique to conda - it's not provided in the Trimmomatic binary distribution (http://www.usadellab.org/cms/uploads/supplementary/Trimmomatic/Trimmomatic-0.36.zip), which only has the jar file.

So I'd say you're right that the tool and the conda dependency resolver are not compatible (conda is essentially providing something different to the toolshed version).

One solution could be to modify the tool wrapper to handle the case when the conda `trimmomatic` is present, and attempt to set the `TRIMMOMATIC_DIR`/`TRIMMOMATIC_ADAPTERS_DIR` env vars accordingly. This looks like it could require a significant rewrite, although I can't see a way that the tool can be generalised otherwise.

Hopefully this makes sense - please let me know what you think about moving this forward.

**Comment by afgane** [comment]
@martenson summarized it nicely here https://gitter.im/galaxy-iuc/iuc?at=57ee9178be5dec75500bfa0e. However, swapping out the order to runtime dependency resolvers to the following makes Galaxy use the ToolShed package vs. the Conda package and the tool runs:
```
<dependency_resolvers>
  <conda />
  <tool_shed_packages />
  <galaxy_packages />
  <conda versionless="true" />
  <galaxy_packages versionless="true" />
</dependency_resolvers>
```

**Comment by bgruening** [comment]
A little bit more background regarding JAVA tools and environment variables.

This one `-jar \$TRIMMOMATIC_DIR/trimmomatic-0.36.jar --help` is not possible in Conda. You can not set an ENV var during installation. We are using a script (https://github.com/bioconda/bioconda-recipes/blob/master/recipes/trimmomatic/trimmomatic.sh), nowadays a python script, that wrapps the JAVA magic into a single executable `trimmomatic`. 

The above command becomes `trimmomatic --help`, way easier to handle. But both versions are not compatible. We did a little bit of bash magic to support Conda and TS dependencies in parallel like here: https://github.com/galaxyproject/tools-iuc/blob/master/tool_collections/snpsift/snpSift_macros.xml#L13 and it seems to work.

This will hopefully all go away if we drop TS dependencies in newer versions.

**Comment by pjbriggs** [comment]
@bgruening et al a couple of questions:

1. Do I need to consider updating the tool to be more compatible with conda? If so then what needs to be done?

2. Understandably the focus of this thread has been on getting the tool to run, but for this tool there is the additional issue of locating trimmomatic's reference data (specifically, the adapter files used by the `ILLUMINACLIP` option).

In the tool command this is located by using an additional variable `TRIMMOMATIC_ADAPTERS_DIR` which is set when the tool dependency is installed from toolshed i.e.

    ...
    ## ILLUMINACLIP option
    #if $illuminaclip.do_illuminaclip
        ILLUMINACLIP:\$TRIMMOMATIC_ADAPTERS_DIR/$illuminaclip.adapter_fasta:$illuminaclip.seed_mismatches:$illuminaclip.palindrome_clip_threshold:$illuminaclip.simple_clip_threshold
    #end if
    ...

It appears that the data is also distributed with the conda version but to locate it requires some backtracking from the location of the `trimmomatic` executable e.g. something like:

    $(dirname $(which trimmomatic))/../share/trimmomatic/adapters

I guess this would work in the tool wrapper? It looks inelegant, and possibly rather fragile - do you know a better way to handle this? 

Please let me know what you think, thanks.

**Comment by bgruening** [comment]
> @bgruening et al a couple of questions:
Do I need to consider updating the tool to be more compatible with conda? If so then what needs to be done?

That would be great!!! Please use the hack from snpsift which I posted above or consider to drop tool_depenencies entirely, if you feel comfortable about this.

> Understandably the focus of this thread has been on getting the tool to run, but for this tool there is the additional issue of locating trimmomatic's reference data (specifically, the adapter files used by the ILLUMINACLIP option).

> It appears that the data is also distributed with the conda version but to locate it requires some backtracking from the location of the trimmomatic executable e.g. something like:

```
$(dirname $(which trimmomatic))/../share/trimmomatic/adapters
```

> I guess this would work in the tool wrapper?

Yes!

>  It looks inelegant, and possibly rather fragile - do you know a better way to handle this?

No, I don't know any way to make this better. Is there no default path trimomatic is expecting this data relative to the binary?

We could enhance the trimmomatic conda package to include the path by default, but this is hacky as well.

Sorry to not be more helpful :)
Bjoern

**Comment by pjbriggs** [comment]
@bgruening thanks that is indeed immensely helpful. I'll reopen this issue and implement the changes when I get a chance to take a proper look. Thanks again for your comments.

**Comment by pjbriggs** [comment]
@bgruening there is now a WIP pull request #23 where I've begun trying to address this along the lines of your suggestions.

**Comment by pjbriggs** [comment]
@afgane @bgruening trimmomatic tool now updated to support conda dependency resolver and pushed to the main and test toolsheds.

**Comment by bgruening** [comment]
Yeah. This is great! Sorry I was not able to test it this week. So many releases ... :(

**Comment by martenson** [comment]
thank you very much @pjbriggs ! 🎉

**Comment by pjbriggs** [comment]
@martenson u r welcome
