### ISSUE TITLE
Is trimmomatic synced with toolshed?

### ISSUE THREAD

**Issue by nekrut** [fls-bioinformatics-core/galaxy-tools#32]
The tool outputs two collections with identical names: one with paired and another with unpaired reads. Yet because they has identical names it is almost unusable in a large history. We have just pulled the recent (36.2) version from toolshed, yet it also outputs two identiacally named collection. I see the following in toolshed:

```
 <output_collection name="fastq_out_paired" type="paired">
        <element name="forward" file="trimmomatic_pe_r1_paired_out1.fastq" />
        <element name="reverse" file="trimmomatic_pe_r2_paired_out1.fastq" />
      </output_collection>
      <output_collection name="fastq_out_unpaired" type="paired">
        <element name="forward" file="trimmomatic_pe_r1_unpaired_out1.fastq" />
        <element name="reverse" file="trimmomatic_pe_r2_unpaired_out1.fastq" />
      </output_collection>
```

but in github version we see this:

```
<collection name="fastq_out_paired" type="paired" label="${tool.name} on ${readtype.fastq_pair.name}: paired">
      <filter>readtype['single_or_paired'] == "collection"</filter>
      <data name="forward" label="${tool.name} on ${readtype.fastq_pair.forward.name} (R1 paired)" format_source="fastq_pair['forward']"/>
      <data name="reverse" label="${tool.name} on ${readtype.fastq_pair.reverse.name} (R2 paired)" format_source="fastq_pair['reverse']"/>
    </collection>
      <collection name="fastq_out_unpaired" type="paired" label="${tool.name} on ${readtype.fastq_pair.name}: unpaired">
        <filter>readtype['single_or_paired'] == "collection"</filter>
        <data name="forward" label="${tool.name} on ${readtype.fastq_pair.forward.name} (R1 unpaired)" format_source="fastq_pair['forward']"/>
        <data name="reverse" label="${tool.name} on ${readtype.fastq_pair.reverse.name} (R2 unpaired)" format_source="fastq_pair['reverse']"/>
    </collection>
```

both seem to be 0.36.2. Can you guys **please** update toolshed version so we can use the proper collection naming.

**Comment by mvdbeek** [comment]
There are 2 things going on here:
 - The toolshed version is up-to-date, are you sure you're using pjbriggs repo? @pvanheus can you deprecate your version? I think @pjbriggs repo contains all necessary changes, right?
 - The collection naming with the current version is not working properly (everything is "Trimmomatic on collection NN"), I'll have a look at what's going on there

**Comment by pvanheus** [comment]
@mvdbeek I'd happily deprecate our version of the repo - how do I do that?

**Comment by mvdbeek** [comment]
You login into the toolshed, you look up trimmomatic, and then in the top right corner you have the Repository Actions button, with the option "Mark repository as deprecated".

**Comment by pjbriggs** [comment]
@mvdbeek PR merged and test and main toolshed versions updated. Thanks for fixing so promptly!

**Comment by pjbriggs** [comment]
Closing as it's fixed as far as I can tell; plz re-open if you disagree!
