### ISSUE TITLE
Trimmomatic wrapper does not catch java exception

### ISSUE THREAD

**Issue by AsierGonzalez** [fls-bioinformatics-core/galaxy-tools#42]
Hello,

While running trimmomatic on galaxy using the wrapper you developed we are having issues with some jobs that fail at the java level (`java.io.IOException: Input/output error`) without being detected by galaxy. The consequence is that the tool keeps running in galaxy (and so do galaxy_X.sh and tool_script.sh) even though the trimmomatic jar already failed.

@AjitPS and I have been looking at the wrapper and we think the reason for this is the **&&** in the following line:

`tee trimmomatic.log &&
  if [ -z "\$(tail -1 trimmomatic.log | grep "Completed successfully")" ]; then echo "Trimmomatic did not finish successfully" >&2`

As we understand it, the _if_ after the _&&_ will only be processed if the pipe (which included the jar) finishes successfully, which will not happen if it fails. We think that this could be fixed replacing the _&&_ by a semicolon, as follows:

`tee trimmomatic.log;
  if [ -z "\$(tail -1 trimmomatic.log | grep "Completed successfully")" ]; then echo "Trimmomatic did not finish successfully" >&2`

In this case, the _if_ will be processed once the pipe finishes.

What do you think? We are happy to fork the repository, make the changes and open a PR if you want.

**Comment by pjbriggs** [comment]
Hello @AsierGonzalez and @AjitPS

Thanks for the detailed report and suggested fix, what you say sounds right to me.

What would be really useful is if you have a small example which can cause the kind of Java-based error condition that you describe. It should then be possible to incorporate as a new test case (I gather it's now possible to make test cases that are expected to fail using `expect_failure="true"` in the `<test>` case, although I have yet to try this). Would you be able to make one that we can use?

Either way if you'd like to make a PR with the changes then please go ahead and we can take it from there.

Thanks for your interest in the Trimmomatic tool.

Peter
