### ISSUE TITLE
Trimmomatic version 0.38 is available

### ISSUE THREAD

**Issue by pjbriggs** [fls-bioinformatics-core/galaxy-tools#63]
Trimmomatic 0.38 is now available:

http://www.usadellab.org/cms/?page=trimmomatic

Once this version is also available in bioconda then the Galaxy tool can also be updated.

**Comment by Yingjie-ZhangOA** [comment]
Trimmomatic 0.38 is available  in bioconda, will this version of Trimmomatic be implemented in Galaxy anytime soon? thx!
[https://bioconda.github.io/recipes/trimmomatic/README.html](url)

**Comment by pjbriggs** [comment]
@Yingjie-ZhangOA the tool has now been updated for Trimmomatic 0.38, and the updated version is available from the tool shed:
https://toolshed.g2.bx.psu.edu/view/pjbriggs/trimmomatic/898b67846b47
