### ISSUE TITLE
Trimmomatic: Separate report output for use in MultiQC?

### ISSUE THREAD

**Issue by sveinugu** [fls-bioinformatics-core/galaxy-tools#66]
The log is currently (at least as of 0.36.5) printing the report into stdout which in Galaxy is shown using the "info" icon. However, it is then not readable by the MultiQC tool, which has support for parsing Trimmomatic output.

Could you move the stdout report into a new history element? Could also be added as an option (e.g., "print report to a new history element?").

What do you think?

**Comment by pjbriggs** [comment]
Hello @sveinugu 

Thanks for your suggestion - @bernt-matthias has now made some updates (in PR #68) which add the option to output the trimmomatic log for input into MultiQC, and these changes are in version 0.36.6 of the tool which is available on the toolshed.

**Comment by sveinugu** [comment]
Cool! Thanks.
