### ISSUE TITLE
Trimmomatic error: unable identify Phred quality encoding

### ISSUE THREAD

**Issue by gallardoalba** [fls-bioinformatics-core/galaxy-tools#79]
An user reported this error.

![Screenshot from 2021-04-10 01-40-22](https://user-images.githubusercontent.com/26678117/114250755-081e8600-999f-11eb-83b0-d52af0dca866.png)

The error seems to be caused by Trimommatic's inability to identify the Phred encoding. In order to solve it, it would be necessary to include the possibility to select a specific encoding in the tool  [-phred33|-phred64].

**Comment by pjbriggs** [comment]
Hello @gallardoalba thanks for the report. When I have an opportunity I will look at implementing the `-phred33|-phred64' options.

(Also: if you're able to provide a small subset of reads from your input Fastq pair which exhibit the problem above then that would be very helpful when it comes to testing - thanks)

**Comment by pjbriggs** [comment]
Addressed by PR #85.
