### ISSUE TITLE
trimmomatic: please add MAXINFO and AVGQUAL

### ISSUE THREAD

**Issue by mictadlo** [fls-bioinformatics-core/galaxy-tools#8]
HI @pjbriggs,
Could you please add MAXINFO and and AVGQUAL to your Trimmomatic Galaxy wrapper ( http://www.usadellab.org/cms/uploads/supplementary/Trimmomatic/TrimmomaticManual_V0.32.pdf )?

Thank you in advance.

Mic

**Comment by pjbriggs** [comment]
Hello @mictadlo 
Thanks - I've created an initial pull request (PR #9) which implements these two operations. When I get an opportunity I'll finish testing and push to the toolshed.
Best wishes
Peter

**Comment by pjbriggs** [comment]
@mictadlo the Trimmomatic wrapper has been updated with these changes (and also updated to use Trimmomatic 0.36) and added to the toolsheds.
Best wishes
Peter
